# Generated by Django 5.2.8 on 2025-11-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=100)),
                (
                    "location",
                    models.CharField(
                        help_text="Address of the job location", max_length=255
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("translation", "Translation"),
                            ("interpretation", "Interpretation"),
                            ("transcription", "Transcription"),
                            ("other", "Other"),
                        ],
                        default="translation",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-time"],
            },
        ),
    ]
