# Generated by Django 5.2.8 on 2025-11-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="unassigned",
                max_length=50,
            ),
        ),
    ]
