# Generated by Django 5.2.8 on 2025-11-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="requires_dshs_certification",
            field=models.BooleanField(
                default=False, help_text="Does this job require DSHS certification?"
            ),
        ),
    ]
