# Generated by Django 5.2.8 on 2025-11-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_requires_dshs_certification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("medical", "Medical"),
                    ("legal", "Legal"),
                    ("other", "Other"),
                ],
                default="medical",
                max_length=50,
            ),
        ),
    ]
