# Generated by Django 5.2.8 on 2025-11-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_job_job_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="language",
        ),
        migrations.AddField(
            model_name="job",
            name="amharic",
            field=models.BooleanField(default=False, verbose_name="Amharic"),
        ),
        migrations.AddField(
            model_name="job",
            name="farsi",
            field=models.BooleanField(default=False, verbose_name="Farsi"),
        ),
        migrations.AddField(
            model_name="job",
            name="mandarin",
            field=models.BooleanField(default=False, verbose_name="Mandarin"),
        ),
        migrations.AddField(
            model_name="job",
            name="portuguese",
            field=models.BooleanField(default=False, verbose_name="Portuguese"),
        ),
        migrations.AddField(
            model_name="job",
            name="russian",
            field=models.BooleanField(default=False, verbose_name="Russian"),
        ),
        migrations.AddField(
            model_name="job",
            name="somali",
            field=models.BooleanField(default=False, verbose_name="Somali"),
        ),
        migrations.AddField(
            model_name="job",
            name="spanish",
            field=models.BooleanField(default=False, verbose_name="Spanish"),
        ),
        migrations.AddField(
            model_name="job",
            name="tigrinya",
            field=models.BooleanField(default=False, verbose_name="Tigrinya"),
        ),
        migrations.AddField(
            model_name="job",
            name="vietnamese",
            field=models.BooleanField(default=False, verbose_name="Vietnamese"),
        ),
    ]
