# Generated by Django 5.2.8 on 2025-11-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_remove_job_language_job_amharic_job_farsi_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="location",
        ),
        migrations.AddField(
            model_name="job",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="state",
            field=models.CharField(
                default="", help_text="Two-letter state code (e.g., WA)", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="street_address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="zip_code",
            field=models.CharField(default="", max_length=10),
        ),
    ]
