# Generated by Django 5.2.8 on 2025-11-11 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_interpreterprofile_dshs_certified"),
        ("jobs", "0006_remove_job_location_job_city_job_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="assigned_interpreter",
            field=models.ForeignKey(
                blank=True,
                help_text="The interpreter assigned to this job",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="accounts.interpreterprofile",
            ),
        ),
    ]
