# Generated by Django 5.2.8 on 2025-11-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_job_assigned_interpreter"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="mileage_included",
            field=models.BooleanField(
                default=False, help_text="Can mileage be included for this job?"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="payment",
            field=models.IntegerField(
                default=0, help_text="Payment amount for this job"
            ),
        ),
    ]
