# Generated by Django 5.2.8 on 2025-11-11 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_interpreterprofile_dshs_certified"),
        ("jobs", "0008_job_mileage_included_job_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterpreterContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contacted_at", models.DateTimeField(auto_now_add=True)),
                ("message_sent", models.TextField()),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "interpreter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_contacts",
                        to="accounts.interpreterprofile",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interpreter_contacts",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interpreter Contact",
                "verbose_name_plural": "Interpreter Contacts",
                "ordering": ["-contacted_at"],
            },
        ),
    ]
