# Generated by Django 5.2.8 on 2025-11-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterpreterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("email_address", models.EmailField(max_length=254)),
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        help_text="Two-letter state code (e.g., WA)", max_length=2
                    ),
                ),
                ("zip_code", models.CharField(max_length=10)),
                ("amharic", models.BooleanField(default=False, verbose_name="Amharic")),
                ("farsi", models.BooleanField(default=False, verbose_name="Farsi")),
                (
                    "mandarin",
                    models.BooleanField(default=False, verbose_name="Mandarin"),
                ),
                (
                    "portuguese",
                    models.BooleanField(default=False, verbose_name="Portuguese"),
                ),
                ("russian", models.BooleanField(default=False, verbose_name="Russian")),
                ("somali", models.BooleanField(default=False, verbose_name="Somali")),
                ("spanish", models.BooleanField(default=False, verbose_name="Spanish")),
                (
                    "tigrinya",
                    models.BooleanField(default=False, verbose_name="Tigrinya"),
                ),
                (
                    "vietnamese",
                    models.BooleanField(default=False, verbose_name="Vietnamese"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
