# Generated by Django 5.2.8 on 2025-11-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interpreterprofile",
            name="dshs_certified",
            field=models.BooleanField(
                default=False,
                help_text="Is this interpreter DSHS certified?",
                verbose_name="DSHS Certified",
            ),
        ),
    ]
